"""Build CMEMS boundary condition .bc files for v05 mesh.

Adapted from build_cmems_bc_v04AE_d10d12.py for the new v05 .pli (333 nodes
along the open-water boundary generated by dfmt.generate_bndpli_cutland).

Differences vs v04AE_d10d12:
  - PLI: data/processed/mesh_v05/Stagnone_v05.pli  (vs v04AE's 49 nodes)
  - CMEMS source: data/raw/cmems_v05/ (extended bbox to lat 38.30)
  - Output: model/dflowfm_v05/
  - Skip uxuy (hydrolib 1.0.0 vector quantity bug; v04AE 49-node fallback
    doesn't map to v05's 333 nodes; FM derives velocity from WL gradient).
  - Skip per-node Marettimo offset (recompute later; constant for now).

Quantities written:
  - waterlevelbnd_CMEMS_*.bc       (333 nodes, 15-min anfc + tide)
  - salinitybnd_CMEMS_*.bc         (333 nodes, daily 3D reanalysis)
  - temperaturebnd_CMEMS_*.bc      (333 nodes, daily 3D reanalysis)
"""
from __future__ import annotations

try:
    import pip_system_certs.wrapt_requests  # noqa: F401
except ImportError:
    pass

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_NC = PROJECT_ROOT / 'data' / 'raw' / 'cmems_v05'
PLI_FILE = PROJECT_ROOT / 'data' / 'processed' / 'mesh_v05' / 'Stagnone_v05.pli'
DST = PROJECT_ROOT / 'model' / 'dflowfm_v05'

TSTART = pd.Timestamp('2025-07-01 00:00')
TSTOP  = pd.Timestamp('2025-07-13 00:00')
REFDATE = '2025-01-01 00:00:00'


def main():
    if not PLI_FILE.exists():
        raise SystemExit(f'PLI not found: {PLI_FILE}\nRun bnd_shp_to_pli_v05.py first.')
    DST.mkdir(parents=True, exist_ok=True)

    import dfm_tools as dfmt
    import hydrolib.core.dflowfm as hcdfm

    # Monkey-patch for hydrolib 1.0.0 (see memory [[dfm_tools_hydrolib_mismatch_2026]])
    if not hasattr(hcdfm, 'VectorQuantityUnitPairs'):
        from pydantic import BaseModel
        from typing import List, Any

        class _VectorQUPStub(BaseModel):
            vectorname: str
            elementname: List[str]
            quantityunitpair: List[Any]

            class Config:
                arbitrary_types_allowed = True

            def __iter__(self):
                return iter(self.quantityunitpair)

        hcdfm.VectorQuantityUnitPairs = _VectorQUPStub
        print('[monkey-patch] Stubbed hcdfm.VectorQuantityUnitPairs for hydrolib 1.0.0')

    ext_new = hcdfm.ExtModel()
    list_quantities = ['waterlevelbnd', 'salinitybnd', 'temperaturebnd']
    dir_pattern = str(SRC_NC / 'cmems_{ncvarname}_*.nc')

    print(f'PLI:          {PLI_FILE}')
    print(f'Source NCs:   {dir_pattern}')
    print(f'Output:       {DST}')
    print(f'Window:       {TSTART} -> {TSTOP}')
    print(f'Quantities:   {list_quantities}\n')

    dfmt.cmems_nc_to_bc(
        ext_new=ext_new,
        list_quantities=list_quantities,
        tstart=TSTART,
        tstop=TSTOP,
        file_pli=str(PLI_FILE),
        dir_pattern=dir_pattern,
        dir_output=str(DST),
        refdate_str=f'minutes since {REFDATE} +00:00',
    )

    print('\nGenerated .bc files:')
    for bc in sorted(DST.glob('*.bc')):
        print(f'  {bc.name}  ({bc.stat().st_size/1024:.1f} KB)')


if __name__ == '__main__':
    main()
