"""Build v04 per-node waterlevel offset .bc using:

    delta(node_i) = delta_anchor + [MDT(node_i) - MDT(Marettimo)]

Inputs:
- model/dflowfm_v04/Stagnone_dxy01_15m.pli   (49 boundary nodes)
- data/raw/cmems/mdt_static/cmems_mdt_med_pli_bbox.nc  (MDT field)
- delta_anchor: from docs/marettimo_offset_anchor_2025.md (mean obs - mean zos)

Output:
- model/dflowfm_v04/waterlevelbnd_offset_pernode_Stagnone_dxy01_15m.bc
- model/dflowfm_v04/Stagnone_dxy01_15m_new.ext  (updated to reference new file)

Window: Jul 2025 9-day run -> use Jul/2025 monthly delta = +0.4812 m
        (annual mean delta would be +0.4489 m, ~3 cm lower)
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import xarray as xr

PROJECT_ROOT = Path(__file__).resolve().parent.parent

V04_DIR = PROJECT_ROOT / 'model' / 'dflowfm_v04'
PLI_FILE = V04_DIR / 'Stagnone_dxy01_15m.pli'
MDT_FILE = (PROJECT_ROOT / 'data' / 'raw' / 'cmems' / 'mdt_static'
            / 'cmems_mdt_med_pli_bbox.nc')
EXT_NEW = V04_DIR / 'Stagnone_dxy01_15m_new.ext'
BC_OUT = V04_DIR / 'waterlevelbnd_offset_pernode_Stagnone_dxy01_15m.bc'

# Marettimo gauge
MARETTIMO_LON = 12.0766
MARETTIMO_LAT = 37.9662

# Delta anchor for Jul 2025 (monthly mean from marettimo_offset_anchor_2025.md)
DELTA_ANCHOR_JUL = 0.4812
# Annual mean (alternative): 0.4489

OLD_OFFSET_FILE = 'waterlevelbnd_constant_Stagnone_dxy01_15m.bc'
NEW_OFFSET_FILE = BC_OUT.name


def read_pli(path: Path) -> tuple[list[str], np.ndarray]:
    names: list[str] = []
    coords: list[tuple[float, float]] = []
    with path.open('r') as f:
        f.readline()  # block name
        n_pts, n_dims = map(int, f.readline().split())
        for _ in range(n_pts):
            parts = f.readline().split()
            x, y = float(parts[0]), float(parts[1])
            name = parts[2] if len(parts) > 2 else ''
            names.append(name)
            coords.append((x, y))
    return names, np.array(coords)


def main() -> int:
    print('=== v04 per-node WL offset .bc ===')
    print()
    print(f'Reading PLI: {PLI_FILE}')
    names, coords = read_pli(PLI_FILE)
    print(f'  {len(names)} nodes, lon=[{coords[:,0].min():.4f},{coords[:,0].max():.4f}], '
          f'lat=[{coords[:,1].min():.4f},{coords[:,1].max():.4f}]')

    print(f'\nReading MDT: {MDT_FILE}')
    ds = xr.open_dataset(MDT_FILE).squeeze()
    print(f'  vars={list(ds.data_vars)}, coords={list(ds.coords)}')
    if 'longitude' in ds.coords:
        ds = ds.rename({'longitude': 'lon', 'latitude': 'lat'})
    mdt = ds['mdt']
    print(f'  mdt range=[{float(mdt.min()):.4f},{float(mdt.max()):.4f}], '
          f'mean={float(mdt.mean()):.4f}')

    # Sample MDT at Marettimo (linear interp - MDT is smooth)
    mdt_marettimo = float(mdt.interp(lon=MARETTIMO_LON, lat=MARETTIMO_LAT))
    print(f'\nMDT at Marettimo ({MARETTIMO_LON:.4f},{MARETTIMO_LAT:.4f}) = {mdt_marettimo:+.4f} m')

    # Sample MDT at each PLI node (linear interp)
    mdt_nodes = np.array([
        float(mdt.interp(lon=x, lat=y)) for x, y in coords
    ])
    print(f'MDT at PLI nodes: range=[{mdt_nodes.min():+.4f},{mdt_nodes.max():+.4f}], '
          f'mean={mdt_nodes.mean():+.4f}')

    # Compute delta per node
    delta_nodes = DELTA_ANCHOR_JUL + (mdt_nodes - mdt_marettimo)
    print(f'\ndelta_anchor (Jul/2025) = {DELTA_ANCHOR_JUL:+.4f} m')
    print(f'delta(node) range = [{delta_nodes.min():+.4f},{delta_nodes.max():+.4f}], '
          f'spread = {delta_nodes.max() - delta_nodes.min():.4f} m')

    # Write per-node .bc file (constant value per [Forcing] block)
    print(f'\nWriting {BC_OUT.name}')
    with BC_OUT.open('w', encoding='ascii', newline='\n') as f:
        f.write('[General]\n')
        f.write('fileVersion           = 1.01\n')
        f.write('fileType              = boundConds\n')
        f.write('\n')
        f.write('# v04: per-node waterlevel offset = anchor(Marettimo Jul/2025)\n')
        f.write(f'#       + [MDT(node) - MDT(Marettimo)]\n')
        f.write(f'# delta_anchor (Jul/2025) = {DELTA_ANCHOR_JUL:+.4f} m\n')
        f.write(f'# MDT(Marettimo)          = {mdt_marettimo:+.4f} m\n')
        f.write(f'# Source: docs/marettimo_offset_anchor_2025.md\n')
        f.write(f'#         data/raw/cmems/mdt_static/cmems_mdt_med_pli_bbox.nc\n')
        f.write(f'# Generated by scripts/build_v04_offset_bc.py\n')
        f.write('\n')
        for name, (x, y), mdt_n, d in zip(names, coords, mdt_nodes, delta_nodes):
            f.write('[Forcing]\n')
            f.write(f'name                  = {name}\n')
            f.write(f'function              = constant\n')
            f.write(f'quantity              = waterlevelbnd\n')
            f.write(f'unit                  = m\n')
            f.write(f'# lon={x:.6f} lat={y:.6f} mdt={mdt_n:+.4f}\n')
            f.write(f'{d:.4f}\n')
            f.write('\n')

    # Update Stagnone_dxy01_15m_new.ext: replace constant filename with per-node file
    print(f'\nUpdating {EXT_NEW.name}')
    text = EXT_NEW.read_text(encoding='utf-8')
    if OLD_OFFSET_FILE in text:
        text = text.replace(OLD_OFFSET_FILE, NEW_OFFSET_FILE)
        # Add a comment marker if not present
        if 'v04: per-node WL offset' not in text:
            head_marker = '[General]'
            insert = (f'# v04: per-node WL offset replaces constant +0.4208 m.\n'
                      f'#      delta_anchor(Jul/2025) = {DELTA_ANCHOR_JUL:+.4f} m,\n'
                      f'#      with MDT spreading across 49 nodes (~6.5 cm).\n'
                      f'#      See scripts/build_v04_offset_bc.py.\n\n')
            text = text.replace(head_marker, insert + head_marker, 1)
        EXT_NEW.write_text(text, encoding='utf-8')
        print(f'  replaced "{OLD_OFFSET_FILE}" -> "{NEW_OFFSET_FILE}"')
    else:
        print(f'  WARN: "{OLD_OFFSET_FILE}" not found in ext_new; skipping ext patch')

    print()
    print('=== Summary ===')
    print(f'  PLI nodes:           {len(names)}')
    print(f'  delta_anchor:        {DELTA_ANCHOR_JUL:+.4f} m (Jul/2025 monthly)')
    print(f'  MDT range at nodes:  {mdt_nodes.min():+.4f} to {mdt_nodes.max():+.4f} m')
    print(f'  delta range at nodes: {delta_nodes.min():+.4f} to {delta_nodes.max():+.4f} m')
    print(f'  Output BC:           {BC_OUT.relative_to(PROJECT_ROOT)}')
    print(f'  Updated ext:         {EXT_NEW.relative_to(PROJECT_ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
