"""
Build Delft3D FM trachytope .arl file from RF v3 seagrass classification.

For each flow link in the mesh, samples classified pixels within RADIUS metres,
computes the area fraction of each trachytope class, and writes the .arl.

Trachytope class mapping (from trachytopes.ttd):
  0  Manning n=0.020  bare sand / unvegetated
  1  Baptist          Cymodocea nodosa (h_v=0.15m, mD=3.2, CD=1.0, Cb=45)
  2  Baptist          Posidonia oceanica (h_v=0.50m, mD=5.0, CD=0.80, Cb=45)
  3  Manning n=0.028  rock / reef plateau

RF v3 class -> trachytope class:
  0 (Unvegetated)          -> 0
  1 (Cymodocea)            -> 1
  2 (Cymo+Caulerpa)        -> 1  (Caulerpa doesn't change canopy height class)
  3 (Posidonia+Caulerpa)   -> 2
  4 (Posidonia atolls)     -> 2
  5 (Posidonia+epiphytes)  -> 2
  7 (Reef plateau)         -> 3
  nodata (-9999)           -> skip  (link gets no entry -> FM uses unifFrictCoef)
"""
from __future__ import annotations
import numpy as np
import xarray as xr
import rasterio
from pathlib import Path
from pyproj import Transformer
import warnings; warnings.filterwarnings('ignore')

ROOT       = Path(__file__).parent.parent
NET_NC     = ROOT / 'model/dflowfm_v04AE/Stagnone_dxy01_15m_net.nc'
CLASS_TIF  = ROOT / 'data/processed/planet2023_rf_v3/classified_seagrass_aug2023_v3.tif'
ARL_OUT    = ROOT / 'data/processed/planet2023_rf_v3/stagnone_trachytopes_v3.arl'

RADIUS = 20        # m — search radius around each edge midpoint
N_TRACHYTOPE = 4   # classes 0-3 in trachytopes.ttd
NODATA = -9999

# RF class -> trachytope class (-1 = no assignment / nodata)
RF_TO_TRAC = {0: 0, 1: 1, 2: 1, 3: 2, 4: 2, 5: 2, 7: 3}

# ── 1. Load mesh edges ──────────────────────────────────────────────────────
print('Loading mesh...')
ds_net = xr.open_dataset(NET_NC)
edge_x = ds_net['mesh2d_edge_x'].values   # (N_edges,) — UTM33N
edge_y = ds_net['mesh2d_edge_y'].values
N_edges = len(edge_x)
print(f'  {N_edges:,} flow links  (lon/lat: {edge_x.min():.3f}-{edge_x.max():.3f}  '
      f'{edge_y.min():.3f}-{edge_y.max():.3f})')

# Convert WGS84 lon/lat -> UTM33N (same CRS as the classified TIF)
xfm = Transformer.from_crs('EPSG:4326', 'EPSG:32633', always_xy=True)
edge_x_utm, edge_y_utm = xfm.transform(edge_x, edge_y)
print(f'  UTM33N extent: X={edge_x_utm.min():.0f}-{edge_x_utm.max():.0f}  '
      f'Y={edge_y_utm.min():.0f}-{edge_y_utm.max():.0f}')

# ── 2. Load classified TIF ─────────────────────────────────────────────────
print('Loading classified TIF...')
with rasterio.open(CLASS_TIF) as ds_r:
    class_map = ds_r.read(1).astype(np.int16)   # (H, W)
    tf        = ds_r.transform
    H, W      = ds_r.height, ds_r.width
    bounds    = ds_r.bounds
    pix_res   = ds_r.res[0]   # 3.0 m

print(f'  Raster: {H}x{W}  res={pix_res}m')
print(f'  Bounds: X={bounds.left:.0f}-{bounds.right:.0f}  '
      f'Y={bounds.bottom:.0f}-{bounds.top:.0f}')

# Map RF classes to trachytope classes (in-place on the raster)
trac_map = np.full_like(class_map, -1, dtype=np.int8)
for rf_c, tr_c in RF_TO_TRAC.items():
    trac_map[class_map == rf_c] = tr_c
# nodata stays -1

# ── 3. Build circular offset kernel ────────────────────────────────────────
r_pix = int(np.ceil(RADIUS / pix_res))    # pixels
dr = np.arange(-r_pix, r_pix + 1)
DC, DR = np.meshgrid(dr, dr)              # col offsets, row offsets
in_circle = (DR**2 + DC**2) <= r_pix**2
DR_c = DR[in_circle].ravel()
DC_c = DC[in_circle].ravel()
N_kernel = len(DR_c)
print(f'\nKernel: radius={RADIUS}m = {r_pix}px  ->  {N_kernel} pixels/link')

# ── 4. Convert edge coords to pixel coords ─────────────────────────────────
# tf.c = left edge, tf.f = top edge, tf.a = pixel width (+), tf.e = pixel height (-)
col_c = ((edge_x_utm - tf.c) / tf.a).astype(int)   # centre column
row_c = ((edge_y_utm - tf.f) / tf.e).astype(int)   # centre row (tf.e < 0)

# Edges within TIF extent (with margin for kernel)
margin = r_pix + 1
in_tif = ((col_c >= margin) & (col_c < W - margin) &
          (row_c >= margin) & (row_c < H - margin))
print(f'  {in_tif.sum():,} / {N_edges:,} links within TIF extent')

# ── 5. Sample and write .arl ───────────────────────────────────────────────
print('Building .arl...')

n_assigned   = 0
n_skipped    = 0    # all pixels nodata
n_out_of_tif = 0

lines = [
    '* Trachytope area roughness link file — Stagnone DT',
    '* RF v3 seagrass classification, Planet SuperDove Aug 2023',
    '* Generated by build_trachytope_arl.py',
    f'* Search radius: {RADIUS} m  |  Kernel: {N_kernel} px  |  Pixel res: {pix_res} m',
    f'* Trachytope classes: 0=sand(n=0.020), 1=Cymodocea(Baptist), '
    '2=Posidonia(Baptist), 3=rock(n=0.028)',
    '* link_id  n_classes  class_id  fraction  [class_id  fraction  ...]',
]

class_hist_global = np.zeros(N_TRACHYTOPE + 1, dtype=np.int64)  # +1 for nodata

for i in range(N_edges):
    if not in_tif[i]:
        n_out_of_tif += 1
        continue

    # Sample kernel pixels
    rows = row_c[i] + DR_c
    cols = col_c[i] + DC_c

    # Bounds guard (shouldn't be needed with margin check above, but safe)
    valid = (rows >= 0) & (rows < H) & (cols >= 0) & (cols < W)
    tc = trac_map[rows[valid], cols[valid]]

    # Count classified pixels (trac >= 0)
    classified = tc[tc >= 0]
    if len(classified) == 0:
        n_skipped += 1
        continue

    # Area fractions
    counts = np.bincount(classified, minlength=N_TRACHYTOPE).astype(float)
    total  = counts.sum()
    fracs  = counts / total

    # Only write classes with fraction > 0
    present = np.where(fracs > 0)[0]
    parts   = []
    for cls in present:
        parts.extend([str(int(cls)), f'{fracs[cls]:.4f}'])
        class_hist_global[cls] += int(counts[cls])

    lines.append(f'{i+1}  {len(present)}  ' + '  '.join(parts))
    n_assigned += 1

# Insert dimension header after comment block (FM requires n_entries as first non-comment line)
comment_end = next(i for i, l in enumerate(lines) if not l.startswith('*'))
lines.insert(comment_end, str(n_assigned))

# Footer stats
lines.append('* End of file')

ARL_OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')

print(f'\n  Links assigned:      {n_assigned:,}')
print(f'  Links outside TIF:  {n_out_of_tif:,}  (will use MDU unifFrictCoef)')
print(f'  Links all-nodata:   {n_skipped:,}')
print(f'\n  Trachytope class distribution (pixel-weighted):')
total_px = class_hist_global[:N_TRACHYTOPE].sum()
class_names = ['sand', 'Cymodocea(Baptist)', 'Posidonia(Baptist)', 'rock']
for cls in range(N_TRACHYTOPE):
    pct = class_hist_global[cls] / total_px * 100 if total_px > 0 else 0
    print(f'    class {cls} ({class_names[cls]:20s}): {class_hist_global[cls]:8,} px  '
          f'({pct:5.1f}%)')
print(f'\nSaved: {ARL_OUT.name}  ({ARL_OUT.stat().st_size/1e3:.0f} kB)')
